import { cell, type NounEntry } from '../types';

/**
 * Seed noun bank. Chosen to cover: all three genders, the masc.
 * personal/animate/inanimate three-way split, hard vs. soft stems, the
 * dative=locative singular syncretism (fem. -a nouns), the
 * nominative=accusative (inanimate) vs. genitive=accusative
 * (personal/animate) syncretism, virile vs. non-virile plural, and one
 * suppletive/irregular paradigm (dziecko) to exercise the irregular-flag
 * path end to end.
 *
 * Vocative note: vocative forms below follow the standard literary
 * paradigm. In casual speech the nominative frequently substitutes for the
 * vocative, especially for inanimates — flagging that generally here
 * rather than per-entry, since it's a register fact, not a paradigm error.
 */
export const NOUNS: NounEntry[] = [
  {
    id: 'n-kot',
    lemma: 'kot',
    translation: 'cat',
    partOfSpeech: 'noun',
    gender: 'masculine',
    animacy: 'animate',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'masculine animate, hard stem',
    stemHardness: 'hard',
    paradigm: {
      singular: {
        nominative: cell('kot'),
        genitive: cell('kota'),
        dative: cell('kotu'),
        accusative: cell('kota', { syncreticWith: ['genitive'] }),
        instrumental: cell('kotem'),
        locative: cell('kocie', {
          stemAlternation: { from: 't', to: 'ć', mechanism: 'palatalization', description: 't → ć (spelled "ci") before locative/vocative -e' },
        }),
        vocative: cell('kocie', {
          syncreticWith: ['locative'],
          stemAlternation: { from: 't', to: 'ć', mechanism: 'palatalization', description: 't → ć (spelled "ci") before locative/vocative -e' },
        }),
      },
      plural: {
        nominative: cell('koty'),
        genitive: cell('kotów'),
        dative: cell('kotom'),
        accusative: cell('koty', { syncreticWith: ['nominative'] }),
        instrumental: cell('kotami'),
        locative: cell('kotach'),
        vocative: cell('koty'),
      },
    },
    notes: 'Non-virile plural throughout — animals pattern with non-virile agreement even though they are grammatically animate in the singular.',
  },
  {
    id: 'n-stol',
    lemma: 'stół',
    translation: 'table',
    partOfSpeech: 'noun',
    gender: 'masculine',
    animacy: 'inanimate',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'masculine inanimate, hard stem',
    stemHardness: 'hard',
    paradigm: {
      singular: {
        nominative: cell('stół'),
        genitive: cell('stołu'),
        dative: cell('stołowi'),
        accusative: cell('stół', { syncreticWith: ['nominative'] }),
        instrumental: cell('stołem'),
        locative: cell('stole', {
          stemAlternation: { from: 'ł', to: 'l', mechanism: 'l-hardening', description: 'ł → l before locative/vocative -e (historical hardening, not palatalization proper)' },
        }),
        vocative: cell('stole', { syncreticWith: ['locative'] }),
      },
      plural: {
        nominative: cell('stoły'),
        genitive: cell('stołów'),
        dative: cell('stołom'),
        accusative: cell('stoły', { syncreticWith: ['nominative'] }),
        instrumental: cell('stołami'),
        locative: cell('stołach'),
        vocative: cell('stoły'),
      },
    },
    notes: 'ó:o alternation: ó surfaces only in the nominative/accusative singular (closed-syllable outcome); every other cell has plain o.',
  },
  {
    id: 'n-student',
    lemma: 'student',
    translation: 'student',
    partOfSpeech: 'noun',
    gender: 'masculine',
    animacy: 'personal',
    pluralAgreementClass: 'virile',
    declensionClass: 'masculine personal, hard stem',
    stemHardness: 'hard',
    paradigm: {
      singular: {
        nominative: cell('student'),
        genitive: cell('studenta'),
        dative: cell('studentowi'),
        accusative: cell('studenta', { syncreticWith: ['genitive'] }),
        instrumental: cell('studentem'),
        locative: cell('studencie', {
          stemAlternation: { from: 't', to: 'ć', mechanism: 'palatalization', description: 't → ć (spelled "ci") before locative/vocative -e' },
        }),
        vocative: cell('studencie', { syncreticWith: ['locative'] }),
      },
      plural: {
        nominative: cell('studenci', {
          stemAlternation: { from: 't', to: 'ć', mechanism: 'palatalization', description: 't → ć (spelled "ci") in the virile nominative plural' },
        }),
        genitive: cell('studentów'),
        dative: cell('studentom'),
        accusative: cell('studentów', { syncreticWith: ['genitive'] }),
        instrumental: cell('studentami'),
        locative: cell('studentach'),
        vocative: cell('studenci'),
      },
    },
    notes: 'Virile plural: accusative = genitive plural (not nominative), unlike the non-virile pattern seen in kot/stół.',
  },
  {
    id: 'n-nauczyciel',
    lemma: 'nauczyciel',
    translation: 'teacher',
    partOfSpeech: 'noun',
    gender: 'masculine',
    animacy: 'personal',
    pluralAgreementClass: 'virile',
    declensionClass: 'masculine personal, soft stem',
    stemHardness: 'soft',
    paradigm: {
      singular: {
        nominative: cell('nauczyciel'),
        genitive: cell('nauczyciela'),
        dative: cell('nauczycielowi'),
        accusative: cell('nauczyciela', { syncreticWith: ['genitive'] }),
        instrumental: cell('nauczycielem'),
        locative: cell('nauczycielu'),
        vocative: cell('nauczycielu', { syncreticWith: ['locative'] }),
      },
      plural: {
        nominative: cell('nauczyciele'),
        genitive: cell('nauczycieli'),
        dative: cell('nauczycielom'),
        accusative: cell('nauczycieli', { syncreticWith: ['genitive'] }),
        instrumental: cell('nauczycielami'),
        locative: cell('nauczycielach'),
        vocative: cell('nauczyciele'),
      },
    },
    notes: 'Soft stems take locative/vocative -u rather than -e, so there is no consonant alternation to trigger here (contrast kot, student).',
  },
  {
    id: 'n-kobieta',
    lemma: 'kobieta',
    translation: 'woman',
    partOfSpeech: 'noun',
    gender: 'feminine',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'feminine, hard stem, -a',
    stemHardness: 'hard',
    paradigm: {
      singular: {
        nominative: cell('kobieta'),
        genitive: cell('kobiety'),
        dative: cell('kobiecie', {
          syncreticWith: ['locative'],
          stemAlternation: { from: 't', to: 'ć', mechanism: 'palatalization', description: 't → ć (spelled "ci") before dative/locative -e' },
        }),
        accusative: cell('kobietę'),
        instrumental: cell('kobietą'),
        locative: cell('kobiecie', {
          syncreticWith: ['dative'],
          stemAlternation: { from: 't', to: 'ć', mechanism: 'palatalization', description: 't → ć (spelled "ci") before dative/locative -e' },
        }),
        vocative: cell('kobieto'),
      },
      plural: {
        nominative: cell('kobiety'),
        genitive: cell('kobiet'),
        dative: cell('kobietom'),
        accusative: cell('kobiety', { syncreticWith: ['nominative'] }),
        instrumental: cell('kobietami'),
        locative: cell('kobietach'),
        vocative: cell('kobiety'),
      },
    },
  },
  {
    id: 'n-ziemia',
    lemma: 'ziemia',
    translation: 'earth / land',
    partOfSpeech: 'noun',
    gender: 'feminine',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'feminine, soft stem, -a',
    stemHardness: 'soft',
    paradigm: {
      singular: {
        nominative: cell('ziemia'),
        genitive: cell('ziemi'),
        dative: cell('ziemi', { syncreticWith: ['locative', 'genitive'] }),
        accusative: cell('ziemię'),
        instrumental: cell('ziemią'),
        locative: cell('ziemi', { syncreticWith: ['dative', 'genitive'] }),
        vocative: cell('ziemio'),
      },
      plural: {
        nominative: cell('ziemie'),
        genitive: cell('ziem', {
          uncertain: true,
          uncertainNote: 'Zero-ending genitive plural for soft -a stems in labial-final position (m) — confirm before treating as settled; attested in set phrases ("ziemie polskie" / "podział ziem"), but I want a second check on the general rule.',
        }),
        dative: cell('ziemiom'),
        accusative: cell('ziemie', { syncreticWith: ['nominative'] }),
        instrumental: cell('ziemiami'),
        locative: cell('ziemiach'),
        vocative: cell('ziemie'),
      },
    },
    notes: 'Already-soft stem (palatal mi), so no orthographic consonant alternation shows up across the paradigm — contrast with kobieta, where -a is hard and t must palatalize.',
  },
  {
    id: 'n-noc',
    lemma: 'noc',
    translation: 'night',
    partOfSpeech: 'noun',
    gender: 'feminine',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'feminine, consonant-stem (i-declension), soft/functionally-soft',
    stemHardness: 'soft',
    paradigm: {
      singular: {
        nominative: cell('noc'),
        genitive: cell('nocy', { syncreticWith: ['dative', 'locative', 'vocative'] }),
        dative: cell('nocy', { syncreticWith: ['genitive', 'locative', 'vocative'] }),
        accusative: cell('noc', { syncreticWith: ['nominative'] }),
        instrumental: cell('nocą'),
        locative: cell('nocy', { syncreticWith: ['genitive', 'dative', 'vocative'] }),
        vocative: cell('nocy', { syncreticWith: ['genitive', 'dative', 'locative'] }),
      },
      plural: {
        nominative: cell('noce'),
        genitive: cell('nocy'),
        dative: cell('nocom'),
        accusative: cell('noce', { syncreticWith: ['nominative'] }),
        instrumental: cell('nocami'),
        locative: cell('nocach'),
        vocative: cell('noce'),
      },
    },
    notes: 'Zero-ending nominative singular, no ending at all (not -a, not -i): this class is a separate feminine paradigm from kobieta/ziemia, not a variant of it.',
  },
  {
    id: 'n-okno',
    lemma: 'okno',
    translation: 'window',
    partOfSpeech: 'noun',
    gender: 'neuter',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'neuter, hard stem, -o',
    stemHardness: 'hard',
    paradigm: {
      singular: {
        nominative: cell('okno'),
        genitive: cell('okna'),
        dative: cell('oknu'),
        accusative: cell('okno', { syncreticWith: ['nominative'] }),
        instrumental: cell('oknem'),
        locative: cell('oknie', {
          stemAlternation: { from: 'n', to: 'ń', mechanism: 'palatalization', description: 'n → ń (spelled "ni") before locative -e' },
        }),
        vocative: cell('okno', { syncreticWith: ['nominative'] }),
      },
      plural: {
        nominative: cell('okna'),
        genitive: cell('okien', {
          stemAlternation: {
            from: '∅',
            to: 'e',
            mechanism: 'vowel-epenthesis',
            description: 'fleeting -e- inserted to break up the kn cluster in the zero-ending genitive plural (okno → okien, not *okn)',
          },
        }),
        dative: cell('oknom'),
        accusative: cell('okna', { syncreticWith: ['nominative'] }),
        instrumental: cell('oknami'),
        locative: cell('oknach'),
        vocative: cell('okna'),
      },
    },
  },
  {
    id: 'n-mieszkanie',
    lemma: 'mieszkanie',
    translation: 'apartment',
    partOfSpeech: 'noun',
    gender: 'neuter',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'neuter, soft stem, -e (deverbal -anie type)',
    stemHardness: 'soft',
    paradigm: {
      singular: {
        nominative: cell('mieszkanie'),
        genitive: cell('mieszkania'),
        dative: cell('mieszkaniu', { syncreticWith: ['locative'] }),
        accusative: cell('mieszkanie', { syncreticWith: ['nominative'] }),
        instrumental: cell('mieszkaniem'),
        locative: cell('mieszkaniu', { syncreticWith: ['dative'] }),
        vocative: cell('mieszkanie', { syncreticWith: ['nominative'] }),
      },
      plural: {
        nominative: cell('mieszkania'),
        genitive: cell('mieszkań'),
        dative: cell('mieszkaniom'),
        accusative: cell('mieszkania', { syncreticWith: ['nominative'] }),
        instrumental: cell('mieszkaniami'),
        locative: cell('mieszkaniach'),
        vocative: cell('mieszkania'),
      },
    },
    notes: 'Extremely productive pattern — any -anie/-enie deverbal noun (spotkanie, ćwiczenie, etc.) will follow this exact template, so it is worth treating as a "regular class" anchor when adding more vocabulary.',
  },
  {
    id: 'n-dlugopis',
    lemma: 'długopis',
    translation: 'pen',
    partOfSpeech: 'noun',
    gender: 'masculine',
    animacy: 'inanimate',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'masculine inanimate, hard stem',
    stemHardness: 'hard',
    paradigm: {
      singular: {
        nominative: cell('długopis'),
        genitive: cell('długopisu'),
        dative: cell('długopisowi'),
        accusative: cell('długopis', { syncreticWith: ['nominative'] }),
        instrumental: cell('długopisem'),
        locative: cell('długopisie', {
          stemAlternation: { from: 's', to: 'ś', mechanism: 'palatalization', description: 's → ś (spelled "si") before locative/vocative -e' },
        }),
        vocative: cell('długopisie', { syncreticWith: ['locative'] }),
      },
      plural: {
        nominative: cell('długopisy'),
        genitive: cell('długopisów'),
        dative: cell('długopisom'),
        accusative: cell('długopisy', { syncreticWith: ['nominative'] }),
        instrumental: cell('długopisami'),
        locative: cell('długopisach'),
        vocative: cell('długopisy'),
      },
    },
  },
  {
    id: 'n-uniwersytet',
    lemma: 'uniwersytet',
    translation: 'university',
    partOfSpeech: 'noun',
    gender: 'masculine',
    animacy: 'inanimate',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'masculine inanimate, hard stem',
    stemHardness: 'hard',
    paradigm: {
      singular: {
        nominative: cell('uniwersytet'),
        genitive: cell('uniwersytetu'),
        dative: cell('uniwersytetowi'),
        accusative: cell('uniwersytet', { syncreticWith: ['nominative'] }),
        instrumental: cell('uniwersytetem'),
        locative: cell('uniwersytecie', {
          stemAlternation: { from: 't', to: 'ć', mechanism: 'palatalization', description: 't → ć (spelled "ci") before locative/vocative -e' },
        }),
        vocative: cell('uniwersytecie', { syncreticWith: ['locative'] }),
      },
      plural: {
        nominative: cell('uniwersytety'),
        genitive: cell('uniwersytetów'),
        dative: cell('uniwersytetom'),
        accusative: cell('uniwersytety', { syncreticWith: ['nominative'] }),
        instrumental: cell('uniwersytetami'),
        locative: cell('uniwersytetach'),
        vocative: cell('uniwersytety'),
      },
    },
    notes: 'na + accusative for motion toward ("Idę na uniwersytet") vs. na + locative for static location ("Jestem na uniwersytecie") — the case alone doesn\'t disambiguate; the preposition-governed accusative/locative contrast does. Worth its own drill pair once prepositional government is in scope.',
  },
  {
    id: 'n-dziecko',
    lemma: 'dziecko',
    translation: 'child',
    partOfSpeech: 'noun',
    gender: 'neuter',
    pluralAgreementClass: 'nonvirile',
    declensionClass: 'neuter, velar stem, -o (irregular/suppletive plural)',
    stemHardness: 'hard',
    irregular: true,
    irregularNote:
      'Plural is suppletive ("dzieci", not a regular reflex of the singular stem). Declension aside, dzieci is also a genuine, lexically fixed exception to the general "human referent → virile agreement" rule: despite denoting people, it takes NON-virile agreement throughout — "Dzieci były grzeczne" (były, not byli), "grzeczne dzieci" (grzeczne, not grzeczni). A clause generator that infers agreement class from animacy/personhood alone will get this word wrong with full confidence; pluralAgreementClass is set explicitly below for exactly that reason. Treat the whole entry as memorize-directly rather than pattern-generalizable.',
    paradigm: {
      singular: {
        nominative: cell('dziecko'),
        genitive: cell('dziecka'),
        dative: cell('dziecku', { syncreticWith: ['locative'] }),
        accusative: cell('dziecko', { syncreticWith: ['nominative'] }),
        instrumental: cell('dzieckiem'),
        locative: cell('dziecku', {
          syncreticWith: ['dative'],
        }),
        vocative: cell('dziecko', { syncreticWith: ['nominative'] }),
      },
      plural: {
        nominative: cell('dzieci'),
        genitive: cell('dzieci', {
          syncreticWith: ['nominative', 'accusative', 'vocative'],
        }),
        dative: cell('dzieciom'),
        accusative: cell('dzieci', { syncreticWith: ['nominative', 'genitive', 'vocative'] }),
        instrumental: cell('dziećmi'),
        locative: cell('dzieciach'),
        vocative: cell('dzieci', { syncreticWith: ['nominative', 'genitive', 'accusative'] }),
      },
    },
    notes: 'Locative singular "dziecku" (not "*dziecce"): velar-final stems (k, g) take -u in the locative/vocative singular rather than -e, which sidesteps the k→c / g→dz alternation entirely — contrast this with the dental/alveolar stems above, which do palatalize.',
  },
];
